### PR TITLE
Enable NO_HZ to gain performance

### PR DESCRIPTION
**Pull request by fazibear**
I'm working on an x86_64 embedded system built on the top of nerves. There are some changes to kernel configuration that led to the performance gain.

### CODE REVIEW

**Comment by fhunleth** [comment]
Thanks again for figuring this out!!

**Comment by mobileoverlord** [comment]
I believe that this PR is going to benefit the kiosk x86 systems too. Thanks @fazibear ❤️

**Comment by fazibear** [comment]
Should I include kernel update within this PR or create another one ?

**Comment by fazibear** [comment]
Oh, it was so fast :) Will create another PR with kernel update.

**Pull request merged**
